### ISSUE TITLE
Error while following 02_Userspace-vHost.md , initializing ovs-dpdk :    EAL: Not enough memory available on socket 1! Requested: 2048MB, available: 0MB PANIC in rte_eal_init(): Cannot init memory

### ISSUE THREAD

**Issue by ovsdpdk** [01org/dpdk-ovs#59] opened 2015-03-02 09:41 UTC

**Comment by indexOutOfBound5** [comment] 2015-03-02 14:38
I'm closing this because it is not an issue with dpdk-ovs. 

For setup questions, please use the mailing list. Please remember to read the archives before posting a new question as this helps to reduce spam.

Thanks,
Meghan

**Closed by indexOutOfBound5** 2015-03-02 14:38 UTC

**Comment by ovsdpdk** [comment] 2015-03-03 08:34
Dear Meghan could you please help me out in making choice of branch or tag
of ovs-dpdk since I could not able to differentiate it since I only need to
do is to run openvswitch on fedora / ubuntu only to implement SDN from last
1 month as well as following many different site i.e
https://jipanyang.wordpress.com/tag/dpdk/ as well as your site but nothing
is going in my way until now. What actually is the difference in master ,
development and release. I am new in this professional field and working on
my final year project so i need to implement SDN on openvswitch in dpdk
especially as a part of my fyp!! plz help me out :(

**Comment by indexOutOfBound5** [comment] 2015-03-03 10:24
This is not the correct forum for your requests. This is the issues section of the dpdk-ovs repo. When you post here, it is to say you have found a bug in the code. You have posted a legitimate error message, which is not a bug.

Please use the mailing-list to raise questions regarding setup, you can sign up here: https://lists.01.org/mailman/listinfo/dpdk-ovs

And view the archives here:
https://lists.01.org/pipermail/dpdk-ovs/

The errors you are seeing should have been covered in a previous thread.

If you choose to reply to/post in the mailing-list, please read a guide on mailing-list etiquette first. Openstack have a nice one here:

https://wiki.openstack.org/wiki/MailingListEtiquette

Thanks,
Meghan
